### PR TITLE
Improve mod loading

### PR DESCRIPTION
**Pull request by Fernando-A-Rocha**
Mods will now load in batches of X, with an interval of Y in between batches.

FYI a mod is a group of txd & dff files that will load in the correct order (which is COL>TXD>DFF).

### CODE REVIEW

**Comment by Fernando-A-Rocha** [comment]
values used for testing in example below:
```lua
local AMOUNT_MODS_PER_BATCH = 2
local TIME_MS_BETWEEN_BATCHES = 1000
```

https://streamable.com/ibjfus

**Comment by Dutchman101** [comment]
I suggest you merge it?

**Comment by Fernando-A-Rocha** [comment]
> I suggest you merge it?

I will try something with coroutines first

**Comment by Fernando-A-Rocha** [comment]
image

WIP

**Comment by Fernando-A-Rocha** [comment]
> I suggest you merge it?

Check it now 😄

**Pull request merged**
